import re

with open('lib/l10n/app_localizations.dart', 'r', encoding='utf-8') as f:
    text = f.read()

en_translations = {
    'statusDispatched': 'Dispatched',
    'poUploadedSuccess': 'PO Uploaded Successfully',
    'expressDeliveryOrdersHere': 'Express delivery orders will appear here',
    'orderDetailsTitle': 'Order Details',
    'refresh': 'Refresh',
    'viewPo': 'View PO',
    'addToCart': 'Add to Cart',
    'viewPi': 'View PI',
    'statusPaymentVerified': 'Payment Verified',
    'actionRequired': 'Action Required',
    'itemTotal': 'Item Total',
    'priceBreakdown': 'Price Breakdown',
    'orderInformation': 'Order Information',
    'accountNumber': 'Account Number',
    'verificationInProgress': 'Verification In Progress',
    'continueBtn': 'Continue',
    'piProvidedMsg': 'PI Provided Message',
    'openText': 'Open',
    'awaitingQuotationDesc': 'Awaiting quotation description',
    'paymentProcessingWarning': 'Your payment is being processed. Please wait...',
    'purchaseOrder': 'Purchase Order',
    'attachPo': 'Attach PO',
    'additionalDocuments': 'Additional Documents',
    'failedToSubmitRating': 'Failed to submit rating',
    'orderTimeStr': 'Order Time',
    'submitPaymentBtn': 'Submit Payment',
    'statusWaitingOnCustomer': 'Waiting on Customer',
    'documentsText': 'Documents',
    'orderConfirmed': 'Order Confirmed',
    'uploadScreenshotHint': 'Upload Screenshot',
    'scanQrCodeToPay': 'Scan QR Code to Pay',
    'orderDateStr': 'Order Date',
    'requestedItems': 'Requested Items',
    'quotationReadyDesc': 'Quotation is ready',
    'viewDetails': 'View Details',
    'proformaInvoice': 'Proforma Invoice',
    'orderPlacedSuccessWithoutPayment': 'Order placed successfully without payment',
    'dispatched': 'Dispatched',
    'dispatchedOnStr': 'Dispatched On',
    'orderedBy': 'Ordered By',
    'orderId': 'Order ID',
    'statusInquiry': 'Status Inquiry',
    'paymentVerificationStatus': 'Payment Verification Status',
    'paymentRejectedStatus': 'Payment Rejected',
    'orderPlacedSuccessfullyTitle': 'Order Placed Successfully!',
    'ifscCode': 'IFSC Code',
    'paymentScreenshotUploadedSuccess': 'Payment screenshot uploaded successfully',
    'accountType': 'Account Type',
    'pleaseAttachPaymentScreenshot': 'Please attach payment screenshot',
    'areaText': 'Area',
    'paymentRejectedDesc': 'Payment rejected description',
    'quotationReady': 'Quotation Ready',
    'dispatchedDesc': 'Order has been dispatched',
    'orderConfirmedDesc': 'Your order has been confirmed',
    'choosePaymentOption': 'Choose Payment Option',
    'selectPaymentMethod': 'Select Payment Method',
    'swiftCode': 'SWIFT Code',
    'verificationInProgressDesc': 'Payment verification is in progress',
    'branch': 'Branch',
    'statusPaymentRejected': 'Payment Rejected',
    'paymentVerifiedStatus': 'Payment Verified Status',
    'paymentScreenshot': 'Payment Screenshot',
    'scanUpiHint': 'Scan UPI to pay',
    'orderPlacedSuccessWithPayment': 'Order placed successfully with payment',
    'awaitingQuotation': 'Awaiting Quotation',
    'requestMessage': 'Request Message',
    'orderDispatchedStatus': 'Order Dispatched',
    'statusPaymentVerification': 'Payment Verification',
    'accountName': 'Account Name',
    'bankName': 'Bank Name',
    'attachPaymentScreenshot': 'Attach Payment Screenshot'
}

hi_translations = {
    'statusDispatched': 'डिस्पैच किया गया',
    'poUploadedSuccess': 'PO सफलतापूर्वक अपलोड किया गया',
    'expressDeliveryOrdersHere': 'एक्सप्रेस डिलीवरी ऑर्डर यहां दिखाई देंगे',
    'orderDetailsTitle': 'ऑर्डर विवरण',
    'refresh': 'रिफ्रेश करें',
    'viewPo': 'PO देखें',
    'addToCart': 'कार्ट में जोड़ें',
    'viewPi': 'PI देखें',
    'statusPaymentVerified': 'भुगतान सत्यापित',
    'actionRequired': 'कार्रवाई आवश्यक है',
    'itemTotal': 'आइटम का कुल',
    'priceBreakdown': 'मूल्य विवरण',
    'orderInformation': 'ऑर्डर की जानकारी',
    'accountNumber': 'खाता संख्या',
    'verificationInProgress': 'सत्यापन प्रगति पर है',
    'continueBtn': 'जारी रखें',
    'piProvidedMsg': 'PI प्रदान किया गया',
    'openText': 'खोलें',
    'awaitingQuotationDesc': 'कोटेशन की प्रतीक्षा है',
    'paymentProcessingWarning': 'आपका भुगतान संसाधित किया जा रहा है। कृपया प्रतीक्षा करें...',
    'purchaseOrder': 'परचेज ऑर्डर',
    'attachPo': 'PO संलग्न करें',
    'additionalDocuments': 'अतिरिक्त दस्तावेज़',
    'failedToSubmitRating': 'रेटिंग सबमिट करने में विफल',
    'orderTimeStr': 'ऑर्डर का समय',
    'submitPaymentBtn': 'भुगतान सबमिट करें',
    'statusWaitingOnCustomer': 'ग्राहक की प्रतीक्षा में',
    'documentsText': 'दस्तावेज़',
    'orderConfirmed': 'ऑर्डर पक्का हुआ',
    'uploadScreenshotHint': 'स्क्रीनशॉट अपलोड करें',
    'scanQrCodeToPay': 'भुगतान करने के लिए QR कोड स्कैन करें',
    'orderDateStr': 'ऑर्डर की तारीख',
    'requestedItems': 'अनुरोधित आइटम',
    'quotationReadyDesc': 'कोटेशन तैयार है',
    'viewDetails': 'विवरण देखें',
    'proformaInvoice': 'प्रोफार्मा चालान',
    'orderPlacedSuccessWithoutPayment': 'बिना भुगतान के ऑर्डर सफलतापूर्वक हो गया',
    'dispatched': 'डिस्पैच किया गया',
    'dispatchedOnStr': 'इस दिन डिस्पैच किया गया',
    'orderedBy': 'इन्होंने ऑर्डर किया',
    'orderId': 'ऑर्डर ID',
    'statusInquiry': 'पूछताछ',
    'paymentVerificationStatus': 'भुगतान सत्यापन स्थिति',
    'paymentRejectedStatus': 'भुगतान अस्वीकृत',
    'orderPlacedSuccessfullyTitle': 'ऑर्डर सफलतापूर्वक हो गया!',
    'ifscCode': 'IFSC कोड',
    'paymentScreenshotUploadedSuccess': 'भुगतान स्क्रीनशॉट सफलतापूर्वक अपलोड किया गया',
    'accountType': 'खाते का प्रकार',
    'pleaseAttachPaymentScreenshot': 'कृपया भुगतान स्क्रीनशॉट संलग्न करें',
    'areaText': 'क्षेत्र',
    'paymentRejectedDesc': 'भुगतान अस्वीकृत किया गया',
    'quotationReady': 'कोटेशन तैयार है',
    'dispatchedDesc': 'ऑर्डर डिस्पैच कर दिया गया है',
    'orderConfirmedDesc': 'आपका ऑर्डर पक्का हो गया है',
    'choosePaymentOption': 'भुगतान विकल्प चुनें',
    'selectPaymentMethod': 'भुगतान विधि चुनें',
    'swiftCode': 'SWIFT कोड',
    'verificationInProgressDesc': 'भुगतान सत्यापन प्रगति पर है',
    'branch': 'शाखा',
    'statusPaymentRejected': 'भुगतान अस्वीकृत',
    'paymentVerifiedStatus': 'भुगतान सत्यापित',
    'paymentScreenshot': 'भुगतान स्क्रीनशॉट',
    'scanUpiHint': 'भुगतान के लिए UPI स्कैन करें',
    'orderPlacedSuccessWithPayment': 'भुगतान के साथ ऑर्डर सफलतापूर्वक हो गया',
    'awaitingQuotation': 'कोटेशन की प्रतीक्षा है',
    'requestMessage': 'अनुरोध संदेश',
    'orderDispatchedStatus': 'ऑर्डर डिस्पैच किया गया',
    'statusPaymentVerification': 'भुगतान सत्यापन',
    'accountName': 'खाते का नाम',
    'bankName': 'बैंक का नाम',
    'attachPaymentScreenshot': 'भुगतान स्क्रीनशॉट संलग्न करें'
}

bn_translations = {
    'statusDispatched': 'পাঠানো হয়েছে',
    'poUploadedSuccess': 'PO সফলভাবে আপলোড করা হয়েছে',
    'expressDeliveryOrdersHere': 'এক্সপ্রেস ডেলিভারি অর্ডার এখানে প্রদর্শিত হবে',
    'orderDetailsTitle': 'অর্ডারের বিবরণ',
    'refresh': 'রিফ্রেশ করুন',
    'viewPo': 'PO দেখুন',
    'addToCart': 'কার্টে যোগ করুন',
    'viewPi': 'PI দেখুন',
    'statusPaymentVerified': 'পেমেন্ট যাচাই করা হয়েছে',
    'actionRequired': 'পদক্ষেপ প্রয়োজন',
    'itemTotal': 'আইটেমের মোট',
    'priceBreakdown': 'দামের বিবরণ',
    'orderInformation': 'অর্ডারের তথ্য',
    'accountNumber': 'হিসাব নম্বর',
    'verificationInProgress': 'যাচাইকরণ চলছে',
    'continueBtn': 'চালিয়ে যান',
    'piProvidedMsg': 'PI প্রদান করা হয়েছে',
    'openText': 'খুলুন',
    'awaitingQuotationDesc': 'কোটেশনের জন্য অপেক্ষা করা হচ্ছে',
    'paymentProcessingWarning': 'আপনার পেমেন্ট প্রক্রিয়া করা হচ্ছে। অনুগ্রহ করে অপেক্ষা করুন...',
    'purchaseOrder': 'পারচেজ অর্ডার',
    'attachPo': 'PO সংযুক্ত করুন',
    'additionalDocuments': 'অতিরিক্ত নথি',
    'failedToSubmitRating': 'রেটিং জমা দিতে ব্যর্থ হয়েছে',
    'orderTimeStr': 'অর্ডারের সময়',
    'submitPaymentBtn': 'পেমেন্ট জমা দিন',
    'statusWaitingOnCustomer': 'গ্রাহকের জন্য অপেক্ষারত',
    'documentsText': 'নথিপত্র',
    'orderConfirmed': 'অর্ডার নিশ্চিত করা হয়েছে',
    'uploadScreenshotHint': 'স্ক্রিনশট আপলোড করুন',
    'scanQrCodeToPay': 'পেমেন্ট করতে QR কোড স্ক্যান করুন',
    'orderDateStr': 'অর্ডারের তারিখ',
    'requestedItems': 'অনুরোধ করা আইটেম',
    'quotationReadyDesc': 'কোটেশন প্রস্তুত',
    'viewDetails': 'বিবরণ দেখুন',
    'proformaInvoice': 'প্রোফর্মা ইনভয়েস',
    'orderPlacedSuccessWithoutPayment': 'পেমেন্ট ছাড়াই অর্ডার সফলভাবে দেওয়া হয়েছে',
    'dispatched': 'পাঠানো হয়েছে',
    'dispatchedOnStr': 'পাঠানোর তারিখ',
    'orderedBy': 'অর্ডার করেছেন',
    'orderId': 'অর্ডার আইডি',
    'statusInquiry': 'অনুসন্ধান',
    'paymentVerificationStatus': 'পেমেন্ট যাচাইকরণের অবস্থা',
    'paymentRejectedStatus': 'পেমেন্ট বাতিল করা হয়েছে',
    'orderPlacedSuccessfullyTitle': 'অর্ডার সফলভাবে দেওয়া হয়েছে!',
    'ifscCode': 'IFSC কোড',
    'paymentScreenshotUploadedSuccess': 'পেমেন্ট স্ক্রিনশট সফলভাবে আপলোড করা হয়েছে',
    'accountType': 'হিসাবের ধরন',
    'pleaseAttachPaymentScreenshot': 'অনুগ্রহ করে পেমেন্ট স্ক্রিনশট সংযুক্ত করুন',
    'areaText': 'এলাকা',
    'paymentRejectedDesc': 'পেমেন্ট বাতিল করা হয়েছে',
    'quotationReady': 'কোটেশন প্রস্তুত',
    'dispatchedDesc': 'অর্ডার পাঠানো হয়েছে',
    'orderConfirmedDesc': 'আপনার অর্ডার নিশ্চিত করা হয়েছে',
    'choosePaymentOption': 'পেমেন্ট বিকল্প বেছে নিন',
    'selectPaymentMethod': 'পেমেন্ট পদ্ধতি নির্বাচন করুন',
    'swiftCode': 'SWIFT কোড',
    'verificationInProgressDesc': 'পেমেন্ট যাচাইকরণ চলছে',
    'branch': 'শাখা',
    'statusPaymentRejected': 'পেমেন্ট বাতিল করা হয়েছে',
    'paymentVerifiedStatus': 'পেমেন্ট যাচাই করা হয়েছে',
    'paymentScreenshot': 'পেমেন্ট স্ক্রিনশট',
    'scanUpiHint': 'পেমেন্ট করতে UPI স্ক্যান করুন',
    'orderPlacedSuccessWithPayment': 'পেমেন্ট সহ অর্ডার সফলভাবে দেওয়া হয়েছে',
    'awaitingQuotation': 'কোটেশনের জন্য অপেক্ষারত',
    'requestMessage': 'অনুরোধের বার্তা',
    'orderDispatchedStatus': 'অর্ডার পাঠানো হয়েছে',
    'statusPaymentVerification': 'পেমেন্ট যাচাইকরণ',
    'accountName': 'হিসাবের নাম',
    'bankName': 'ব্যাংকের নাম',
    'attachPaymentScreenshot': 'পেমেন্ট স্ক্রিনশট সংযুক্ত করুন'
}

for locale, trans in [('en', en_translations), ('hi', hi_translations), ('bn', bn_translations)]:
    search_str = f"'{locale}': {{"
    idx = text.find(search_str)
    if idx != -1:
        end_of_line_idx = text.find('\n', idx)
        if end_of_line_idx != -1:
            inserts = []
            for key, val in trans.items():
                if f"'{key}':" not in text[idx:idx+15000]:
                    inserts.append(f"      '{key}': '{val}',")
            
            if inserts:
                insert_str = '\n' + '\n'.join(inserts)
                text = text[:end_of_line_idx] + insert_str + text[end_of_line_idx:]

with open('lib/l10n/app_localizations.dart', 'w', encoding='utf-8') as f:
    f.write(text)

print("Injected 71 missing keys!")
